wired_pea_frontpage:
    resource: "@WiredPeaFrontpageBundle/Resources/config/routing.yml"
    prefix:   /

wired_pea_user:
    resource: "@WiredPeaUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
