name: Django CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
    - name: Linters
      run: |
        poetry run flake8 ./
        poetry run black --check .
        poetry run pylama --ignore=D212,V107 --linters eradicate,mccabe,mypy,pycodestyle,pydocstyle,pyflakes,pylint,radon,vulture,isort ./[
    - name: Run Tests
      run: |
        poetry run ./manage.py test
