<?php

/**
 * @file
 * All the code to use the Google analytics API.
 */

$google_api_path = wiredpea_ga_api_load_library();
if ($google_api_path) {
    require_once($google_api_path);
}
else {
    drupal_set_message(t('The Google client library was not found. Please install that first.'));
}

/**
 * Implements hook_libraries_info().
 */
function wiredpea_ga_api_libraries_info() {
    $libraries['google_analytics'] = array(
        'name' => 'The google analytics API',
        'vendor url' => 'https://developers.google.com/api-client-library/php/',
        'download url' => 'https://github.com/google/google-api-php-client/releases/tag/1.1.2',
        'version arguments' => array(
            'file' => 'Google_Client.php',
            'pattern' => '/LIBVER = "1.1.2"/',
        ),
        'files' => array(
            'js' => array('Google/Client.php'), //this can be a path to the file location like array('lib/simple.js')
        ),
    );

    return $libraries;
}

/**
 * Implements hook_menu().
 */
function wiredpea_ga_api_menu() {
    $items = array();

    $items['ga'] = array(
        'page callback' => 'wiredpea_ga_api_overview_page',
        'access callback' => TRUE,
    );

    return $items;
}

/**
 * Builds the overview page.
 */
function wiredpea_ga_api_overview_page() {
    global $user;
    $full_user = user_load($user->uid);
    $api_token = field_get_items('user', $full_user, 'field_google_analytics_api_key');

    $client = new Google_Client();
    $client->setAuthConfig($api_token[0]['value']);
    $client->setScopes(array('https://www.googleapis.com/auth/analytics.readonly'));

    $analytics = new Google_Service_Analytics($client);

    $core_data = $analytics->data_ga;

    $optParams = array(
        'dimensions' => 'ga:source,ga:keyword',
        'sort' => '-ga:sessions,ga:source',
        'filters' => 'ga:medium==organic',
        'max-results' => '1000'
    );
    $core_data->get(
        'UA-3550192-1',
        '2015-01-01',
        '2015-01-15',
        'ga:sessions',
        $optParams);
}

/**
 * Loads the Google API php library.
 */
function wiredpea_ga_api_load_library() {
    $file = 'autoload.php';
    $library = 'google-api-php-client-1.1.2';

    if (module_exists('libraries') && function_exists('libraries_get_path')) {
        $library_path = libraries_get_path($library) . "/{$file}";
        if (file_exists($library_path)) {
            return $library_path;
        }
    }

    return FALSE;
}
